-- Ejecutar una vez en Supabase > SQL Editor.
-- Es idempotente: crea lo faltante y conserva las tablas/datos existentes.

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  unit text not null default 'unidades',
  current_stock numeric(14,3) not null default 0,
  min_threshold numeric(14,3) not null default 0,
  category text not null default 'materia_prima',
  sku text,
  notes text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products add column if not exists category text not null default 'materia_prima';
alter table public.products add column if not exists sku text;
alter table public.products add column if not exists notes text;
alter table public.products add column if not exists is_active boolean not null default true;
alter table public.products add column if not exists created_at timestamptz not null default now();
alter table public.products add column if not exists updated_at timestamptz not null default now();

-- Normaliza categorías antiguas antes de aplicar la restricción.
update public.products
set category = 'otro'
where category not in ('materia_prima', 'packaging', 'otro');

alter table public.products drop constraint if exists products_category_check;
alter table public.products add constraint products_category_check
  check (category in ('materia_prima', 'packaging', 'otro'));

create table if not exists public.stock_movements (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id),
  type text not null,
  quantity numeric(14,3) not null,
  notes text,
  created_at timestamptz not null default now()
);

alter table public.stock_movements add column if not exists stock_before numeric(14,3);
alter table public.stock_movements add column if not exists stock_after numeric(14,3);

create unique index if not exists products_name_active_unique
  on public.products (lower(name)) where is_active = true;
create index if not exists stock_movements_product_date_idx
  on public.stock_movements (product_id, created_at desc);

create or replace function public.record_stock_movement(
  p_product_id bigint,
  p_type text,
  p_quantity numeric,
  p_notes text default null
) returns public.stock_movements
language plpgsql
security definer
set search_path = public
as $$
declare
  v_product public.products;
  v_movement public.stock_movements;
  v_new_stock numeric;
  v_saved_type text := p_type;
  v_saved_quantity numeric := p_quantity;
begin
  if p_type not in ('in', 'out', 'set') then
    raise exception 'Tipo de movimiento inválido';
  end if;
  if p_quantity < 0 or (p_type <> 'set' and p_quantity = 0) then
    raise exception 'La cantidad debe ser mayor a cero';
  end if;

  select * into v_product from public.products
  where id = p_product_id and is_active = true for update;
  if not found then raise exception 'Producto no encontrado'; end if;

  if p_type = 'set' then
    v_new_stock := p_quantity;
    v_saved_quantity := abs(p_quantity - v_product.current_stock);
    if p_quantity >= v_product.current_stock then v_saved_type := 'in';
    else v_saved_type := 'out'; end if;
  elsif p_type = 'in' then
    v_new_stock := v_product.current_stock + p_quantity;
  else
    v_new_stock := v_product.current_stock - p_quantity;
    if v_new_stock < 0 then
      raise exception 'Stock insuficiente. Disponible: % %', v_product.current_stock, v_product.unit;
    end if;
  end if;

  if v_saved_quantity = 0 then raise exception 'El ajuste no modifica el stock'; end if;

  update public.products
  set current_stock = v_new_stock, updated_at = now()
  where id = p_product_id;

  insert into public.stock_movements
    (product_id, type, quantity, notes, stock_before, stock_after)
  values
    (p_product_id, v_saved_type, v_saved_quantity,
     case when p_type = 'set' then concat('Ajuste de inventario. ', coalesce(p_notes, '')) else p_notes end,
     v_product.current_stock, v_new_stock)
  returning * into v_movement;

  return v_movement;
end;
$$;

create or replace function public.create_product_with_stock(
  p_name text,
  p_unit text,
  p_category text,
  p_min_threshold numeric,
  p_initial_stock numeric default 0,
  p_sku text default null,
  p_notes text default null
) returns public.products
language plpgsql
security definer
set search_path = public
as $$
declare
  v_product public.products;
begin
  if trim(p_name) = '' or trim(p_unit) = '' or p_min_threshold < 0 or p_initial_stock < 0 then
    raise exception 'Datos de producto inválidos';
  end if;

  insert into public.products
    (name, unit, category, min_threshold, current_stock, sku, notes)
  values
    (trim(p_name), p_unit, p_category, p_min_threshold, 0, nullif(trim(p_sku), ''), nullif(trim(p_notes), ''))
  returning * into v_product;

  if p_initial_stock > 0 then
    perform public.record_stock_movement(v_product.id, 'in', p_initial_stock, 'Stock inicial');
    select * into v_product from public.products where id = v_product.id;
  end if;

  return v_product;
end;
$$;
